### ISSUE TITLE
Remove current ToDo backend from Docs

### ISSUE THREAD

**Issue by urirb** [binaris/functions-examples#42]
In order not to confuse our potential new users - please remove this from our docs:
https://dev.binaris.com/tutorials/nodejs/todo-backend/

**Comment by urirb** [comment]
Ryland says he doesn't know how to remove it.

**Comment by michaeladda** [comment]
is the requirement to remove the example from the example repo or the tutorial from the dev site or both?
Shouldn't instead of remove this should be replaced?

**Comment by urirb** [comment]
We should remove the old to do tutorial from the dev site.
Let's decide later if we want to put the new one instead.
BTW - I don't fully understand the consequences of removing it from the example repo - so i don't know what to tell you
