### ISSUE TITLE
image resize example should use random file names

### ISSUE THREAD

**Issue by michaeladda** [binaris/functions-examples#69]
otherwise there's an embedded race in the code as present (`SRCFILE` and `DSTFILE` I'm looking at you) since the yaml has `executionModel: concurrent`.

**Comment by avnerbraverman** [comment]
Thanks for reviewing my code. I can definitely make the change. Just for my
own education: why is this important (and specifically in a sample context)?

**Comment by michaeladda** [comment]
Oh, I looked at the code since it popped in my inbox (probably @rylandg or you tagged me sometime in the PR while I was away).
This is obviously a low priority issue, but once spotted it's silly to ignore, so I just created an issue to track it.

**Comment by avnerbraverman** [comment]
I'd still like to understand why

**Comment by michaeladda** [comment]
Oh, I thought you asked a meta question. Didn't understand it's why there's a potential race.
The container can be used by two concurrent invocations due to the executionModel. Let's call them A and B, and assume A request arrives first, (async) writes to SRCFILE its payload, and (async) starts exec resize. Now B request arrives, (async) writes to SRCFILE its own payload, which happens while A is resizing, which may lead to A output be either corrupt or of B. A similar race exists for DSTFILE.
Using uuid file names, or even embedding the request id in it would obviously eliminate the race.

**Comment by avnerbraverman** [comment]
Right. Thx
